### ISSUE TITLE
object 'icd9_sub_chapters' has overlapping categories

### ISSUE THREAD

**Issue by sargdavid** [jackwasey/icd.data#2] opened 2018-05-25 05:47 UTC
E.g. 290:299 Psychoses and 290:294 Organic Psychotic Conditions
See full list attached.
[overlapping_sub_chapters.xlsx](https://github.com/jackwasey/icd.data/files/2038108/overlapping_sub_chapters.xlsx)

On a closer examination, here are the 4 sub-chapters that include smaller sub-chapters (for now, I remove them manually for the shiny app):
1. Psychoses
2. Fractures
3. Open Wounds
4. Transport Accidents

**Comment by jackwasey** [comment] 2018-06-02 20:54
Yes, this hierarchical distinction isn't captured by `icd`. I'm not sure what the issue is exactly: does `icd` incorrectly have both the hierarchical levels listed?

At this point, having another level between sub-chapter and "major" would be a lot of work. How important do you think this is? Maybe it could be captured in a different data structure.

**Comment by sargdavid** [comment] 2018-06-02 21:08
It doesn't really bother me - I removed these 4 sub-chapters manually, it's rather easy to do inside the code. I'm not sure where these categories came from; if you check on[ icd9data.com](http://www.icd9data.com/2015/Volume1/default.htm), for example, these do not exist. I can send you exact list of overlapping sub-chapters, there are not that many, but I still need to remove them to for the Shiny app. I think it's OK to have them there, as long as users are aware of this issue.

**Comment by jackwasey** [comment] 2018-07-16 19:07
I've look at this again. For consistency, removal of the sub-sub-chapters would be consistent with the other sub-chapter hierarchy. My instinct is to leave these in the `icd9_sub_chapters` structure and to do the easy workarounds, or, possibly, have a second structure called something like `icd9_sub_chapters_extra` which would include them all, then restrict `icd9_sub_chapters` to non-overlapping definitions. What do you think?

**Comment by sargdavid** [comment] 2018-07-18 16:31
I think ..._extra is a good idea but either way is OK, really. Thank you!

**Comment by jackwasey** [comment] 2019-04-02 09:35
This is fixed in soon-to-be-release icd 4.0 . Now we just ignore the intermediate sub-chapter definition, so the data frames are consistent and backward compatible. We can think about adding an updated data frame with the additional designation.

**Closed by jackwasey** 2019-04-02 09:35 UTC
